<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>prg</string>
	</array>
	<key>name</key>
	<string>Fabius</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Single-line comment</string>
			<key>match</key>
			<string>\/\/.*\n?$</string>
			<key>name</key>
			<string>comment.line.double-slash.fabius</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>comment</key>
			<string>Single-line comment</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block.fabius</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(?i:(if|endif|while|enddo|try|except|end|for|next|finally|parameters|global|local|private|public|return|loop|to|else|elseif))\b</string>
			<key>name</key>
			<string>keyword.control.fabius</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(?i:(iif|@))\b</string>
			<key>name</key>
			<string>keyword.other.fabius</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operator</string>
			<key>match</key>
			<string>(:=|&lt;=|&gt;=|[\+\*\-=\/;]|(\b(?i:(and|or|not)\b)))</string>
			<key>name</key>
			<string>keyword.operator.fabius</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String</string>
			<key>match</key>
			<string>".*?"</string>
			<key>name</key>
			<string>string.quoted.single.fabius</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String</string>
			<key>match</key>
			<string>\'.*?\'</string>
			<key>name</key>
			<string>string.quoted.double.fabius</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String</string>
			<key>match</key>
			<string>[^ \w]*?\s*\[.*?\]</string>
			<key>name</key>
			<string>string.quoted.other.fabius</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Language constants</string>
			<key>match</key>
			<string>(\b(?i:(true|false|ReflisPath|OpdataPath))\b|\.t\.|\.f\.)</string>
			<key>name</key>
			<string>constant.other.fabius</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.fabius</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.fabius</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fabius</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variable</string>
			<key>match</key>
			<string>(\(\b[_\w\d]+\b\))(-&gt;)(\b[_\w\d]+\b)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Variable</string>
			<key>match</key>
			<string>~\b(?i:([_\w][_\w\d]*))\b</string>
			<key>name</key>
			<string>variable.parameter.fabius</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fabius</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function call</string>
			<key>match</key>
			<string>\b(?i:([_\w][_\w\d]*))\b\(</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.other.fabius</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variable</string>
			<key>match</key>
			<string>\b([_A-z][_A-z0-9]*)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.fabius</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Language constants</string>
			<key>match</key>
			<string>[\d]+(|\.[\d]+)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fabius</string>
	<key>uuid</key>
	<string>e243dc42-f7a4-4daa-b0df-00ac8690124e</string>
</dict>
</plist>
